### ISSUE TITLE
About 'undetected person'

### ISSUE THREAD

**Issue by jionepak** [caposerenity/DAPS#5]
![image](https://github.com/caposerenity/DAPS/assets/129134919/f9c30db8-b7df-425b-b9d4-3051d2c952a9)

Does "undetected person" mean someone who needs to find it but couldn't find it, or someone who doesn't have to? If it's "someone you don't have to find" does it mean someone who isn't ground truth labeling in the dataset?

**Comment by caposerenity** [comment]
Hi, "undetected person" means **someone who needs to find it but the detection head treated them as negative samples**.

**Comment by jionepak** [comment]
Then why undetected person and background clutter are treated as one category in hard case mining?

**Comment by caposerenity** [comment]
The idea of 'Hybrid Hard Case Mining' is to emply hard nagative samples in detection to support learning of ReID, both undetected person and background clutter are considered as one type of such hard nagative samples. During ReID training (memory loss based), they both only work as nagative samples compared with persons with identities. In a word, they are not one category, but they could work together as  nagative samples for ReID, that's why we call this design '**Hybrid**' hard case mining.
